#!/bin/bash

DIR="/tmp/hadoop-$USER"

# Realização da cópia do input local para o HDFS
bin/hdfs dfs -put matrix input
# Compilação do código java
bin/hadoop com.sun.tools.javac.Main BlockMatrixMultiplication.java
jar cf bl.jar BlockMatrixMultiplication*.class
# Execução da primeira etapa
bin/hadoop jar bl.jar BlockMatrixMultiplication input output
# Exibicão do resultado na tela
bin/hdfs dfs -cat output/*
# Removendo arquivos no HDFS
bin/hdfs dfs -rm -r -f output
bin/hdfs dfs -rm -r -f input
