#!/bin/bash

DIR="/tmp/hadoop-$USER"

# Remoção dos eventuais arquivos temporários locais criados em execuções anteriores
rm -Rf $DIR/*
# Formatação do namenode
bin/hdfs namenode -format
# Inicialização do namenode e do(s) datanode(s)
sbin/start-dfs.sh
sbin/start-yarn.sh
# Criação dos diretórios
bin/hdfs dfs -mkdir /user
bin/hdfs dfs -mkdir /user/$USER
